### ISSUE TITLE
Question on lwe-estimator 

### ISSUE THREAD

**Issue by fionser** [menonsamir/ypir#1]
I used the Python notebook from the mal/lattice-estimator library, and the rought estimation security level seems lower than 128.
Did I use the estimator correctly ? 

<img width="1069" alt="截屏2024-02-27 10 11 06" src="https://github.com/menonsamir/ypir/assets/1809457/fb52890d-05b6-43be-b0d5-f5f351ef3331">

**Comment by menonsamir** [comment]
The ND.DiscreteGaussian function takes a standard deviation $\sigma$ (not the parameter of the subgaussian, $s$); these are related by $s = \sigma \sqrt{2\pi}$. We specify the noise width using the parameter of the subgaussian in the paper. So, I think you should pass 11 and 6.4 to ND.DiscreteGaussian, respectively. Does that makes sense? In addition, the .rough() call does not always produce an estimate matching the full one, so it's important to run `LWE.estimate`.

I get:
<img width="928" alt="image" src="https://github.com/menonsamir/ypir/assets/1719724/16c1fc1e-fbd9-41e2-b3a7-ebabd1daac65">
<img width="906" alt="image" src="https://github.com/menonsamir/ypir/assets/1719724/f0f0e355-3d9c-40d7-a6df-89b4515cfa02">
