### ISSUE TITLE
Is there any non `avx512f` version of code that can be used?

### ISSUE THREAD

**Issue by qxzhou1010** [menonsamir/ypir#3]
Hello, I plan to delve deeper into the code implementation of YPIR. However, my Mac does not support `avx512f`.

During compilation, I encountered a lot of errors and ended up pointing to a function: `fast_matched_dot_deduct_avx512`.

So, is there a non `avx512f` version of the implementation code for `fast_matched_dot_deduct` here?

Thank you very much.

**Comment by llllinyl** [comment]
Hi, I have run into this problem as well. Can you share a copy of the code if you solve it? Thank you very much!

**Comment by menonsamir** [comment]
Yes, the `demo` branch has an implementation that does not require AVX512. If you check out the `demo` branch, and then run `cargo run --release --bin run -- 1073741824`, this should successfully run the basic benchmark test on most systems (even ones without AVX512 or AVX2).
